formating feature failure comment

diff --git a/.github/workflows/lint-and-sample-feature-check.yaml b/.github/workflows/lint-and-sample-feature-check.yaml
--- a/.github/workflows/lint-and-sample-feature-check.yaml
+++ b/.github/workflows/lint-and-sample-feature-check.yaml
@@ -125,7 +125,20 @@ jobs:
                             p
                             }' sampleRunOutput.txt > failure_reason.txt)
             cat failure_reason.txt
-            echo "PR_COMMENT=Hello feature Run failed :: $(cat failure_reason.txt)" >> "$GITHUB_OUTPUT"
+          
+            {
+              echo 'PR_COMMENT<<EOF'
+              echo -n 'Hello feature run failed with the following errors:\n'
+              echo -n '\n'
+              echo -n '```\n'
+              awk '{gsub(/"/, "\\\""); printf "%s\\n", $0}' failure_reason.txt
+              echo -n '```\n'
+              echo -n '\n'
+              echo -n 'For more information on our testing policies, please see our [Testing-Guide](../tree/dev/Testing-Guide.md).\n'
+              echo '\n'
+              echo 'EOF'
+            } >> "$GITHUB_OUTPUT"
+            exit 1
           else
             echo "Hello feature run succeeded."
           fi
