Update lint-and-sample-feature-check.yaml

diff --git a/.github/workflows/lint-and-sample-feature-check.yaml b/.github/workflows/lint-and-sample-feature-check.yaml
--- a/.github/workflows/lint-and-sample-feature-check.yaml
+++ b/.github/workflows/lint-and-sample-feature-check.yaml
@@ -36,12 +36,14 @@ jobs:
 
       - name: Determine comment based on linting results
         id: comment
-        if: ${{ github.event_name == 'pull_request' }}
         run: |
           LINT_ERRORS=""
           if [ -f lintOutput.txt ]; then
               LINT_ERRORS=$(grep -E '[1-9][0-9]*\serror' lintOutput.txt || true)
           fi
+          git branch
+          cat lintOutput.txt
+          
           if [ -n "$LINT_ERRORS" ]; then
             {
               echo 'PR_COMMENT<<EOF'
@@ -55,32 +57,27 @@ jobs:
               echo ""
               echo EOF
             } >> "$GITHUB_OUTPUT"
+            exit 1
           else
             echo "PR_COMMENT=Linting succeeded." >> "$GITHUB_OUTPUT"
           fi
 
-      - name: Fail if linting errors found
-        if: steps.comment.outputs.PR_COMMENT != 'Linting succeeded.'
-        run: exit 1
-
-      - name: Comment on PR
-        if: always()
+      - name: Notify PR on Failure
+        if: ${{ failure() && github.event_name == 'pull_request' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PR_COMMENT: ${{ steps.comment.outputs.PR_COMMENT }}
         run: |
-          if [[ "${{ github.event_name }}" == 'pull_request' && "$PR_COMMENT" != 'Linting and unit tests succeeded.' ]]; then
-            JSON_PAYLOAD=$(jq -n --arg body "$PR_COMMENT" '{"body": $body}')
+          JSON_PAYLOAD=$(jq -n --arg body "$PR_COMMENT" '{"body": $body}')
 
-            echo "Generated JSON payload:"
-            echo "$JSON_PAYLOAD"
+          echo "Generated JSON payload:"
+          echo "$JSON_PAYLOAD"
 
-            curl -X POST \
-              -H "Authorization: Bearer $GITHUB_TOKEN" \
-              -H "Content-Type: application/json" \
-              -d "$JSON_PAYLOAD" \
-              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
-          fi
+          curl -X POST \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "Content-Type: application/json" \
+            -d "$JSON_PAYLOAD" \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
 
   run_testcase:
     runs-on: ubuntu-latest
@@ -90,6 +87,8 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
+        with:
+          ref: ${{ inputs.branch || github.head_ref }}
 
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
@@ -100,48 +99,46 @@ jobs:
         run: yarn install
 
       - name: Run Hello feature
-        run: yarn run cy:run -- --spec "cypress/TestCases/Sample/Hello.feature" --env testSuite="sample",generateLocalReport="false" > samplRunOutput.txt || true
+        run: yarn run cy:run -- --spec "cypress/TestCases/Sample/Hello.feature" --env testSuite="sample",generateLocalReport="false" > sampleRunOutput.txt || true
 
       # To remove ANSI escape characters
-      - name: Remove ANSI escape codes from samplRunOutput.txt
-        run: sed -i "s/\x1B\[[0-9;]*[JKmsu]//g" samplRunOutput.txt
+      - name: Remove ANSI escape codes from sampleRunOutput.txt
+        run: sed -i "s/\x1B\[[0-9;]*[JKmsu]//g" sampleRunOutput.txt
 
       - name: Determine comment based on test results
         id: comment
-        if: ${{ github.event_name == 'pull_request' }}
         run: |
-          if grep -q "0 passing" samplRunOutput.txt; then
+
+          git branch
+          cat sampleRunOutput.txt
+          
+          if grep -q "0 passing" sampleRunOutput.txt; then
             FAILURE_REASON=$(sed -n '/1 failing/,/\[mochawesome\]/ {
                             /1 failing/b
                             /\[mochawesome\]/b
                             p
-                            }' samplRunOutput.txt > failure_reason.txt)
+                            }' sampleRunOutput.txt > failure_reason.txt)
             echo "PR_COMMENT=Hello feature Run failed" >> "$GITHUB_OUTPUT"
+            exit 1
           else
             echo "PR_COMMENT=Hello feature Run Passed." >> "$GITHUB_OUTPUT"
           fi
 
-      - name: Fail if run testcase failed
-        if: steps.comment.outputs.PR_COMMENT != 'Hello feature Run Passed.'
-        run: exit 1
-
-      - name: Comment on PR
-        if: always()
+      - name: Notify PR on Failure
+        if: ${{ failure() && github.event_name == 'pull_request' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PR_COMMENT: ${{ steps.comment.outputs.PR_COMMENT }}
         run: |
-          if [[ "${{ github.event_name }}" == 'pull_request' && "$PR_COMMENT" != 'Hello feature Run Passed.' ]]; then
-            # Read the content of failure_reason.txt into a variable
-            FAILURE_REASON_CONTENT=$(cat failure_reason.txt)
-            JSON_PAYLOAD=$(jq -n --arg body "$PR_COMMENT :: $FAILURE_REASON_CONTENT" '{"body": $body}')
+          # Read the content of failure_reason.txt into a variable
+          FAILURE_REASON_CONTENT=$(cat failure_reason.txt)
+          JSON_PAYLOAD=$(jq -n --arg body "$PR_COMMENT :: $FAILURE_REASON_CONTENT" '{"body": $body}')
 
-            echo "Generated JSON payload:"
-            echo "$JSON_PAYLOAD"
+          echo "Generated JSON payload:"
+          echo "$JSON_PAYLOAD"
 
-            curl -X POST \
-              -H "Authorization: Bearer $GITHUB_TOKEN" \
-              -H "Content-Type: application/json" \
-              -d "$JSON_PAYLOAD" \
-              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
-          fi
+          curl -X POST \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "Content-Type: application/json" \
+            -d "$JSON_PAYLOAD" \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
